services:
  thrive-api:
    build:
      context: .
      args:
        RUBY_VERSION: 3.1.2
        BUNDLE_JOBS: 15
        BUNDLE_RETRY: 2
        UID: 500
        GID: 500
    environment:
      REDIS_HOST: host.docker.internal
      DATABASE_HOST: host.docker.internal
      REDIS_SIDEKIQ_HOST: host.docker.internal
    command: bundle exec rails server -p 8086 -b '0.0.0.0'
    entrypoint: docker/entrypoint.sh
    # for debugging purposes
    # command: /bin/bash
    volumes:
      - ..:/app
    ports:
      - '8086:8086'
    user: ruby
    tty: true
    stdin_open: true
volumes:
  gems: {}
  postgres: {}
  node_modules: {}
  packs: {}
  rails_cache: {}
